/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 3, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2
/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=Wide_ResNet50_2_Weights.IMAGENET1K_V1`. You can also use `weights=Wide_ResNet50_2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
====> Epoch 0 : Average loss: 1.2931
torch.Size([16, 3, 256, 256])
torch.Size([16, 3, 256, 256])
Pred shape: (torch.Size([16, 3, 256, 256]), torch.Size([3, 256, 256])), true shape: (16, tensor(0))
Traceback (most recent call last):
  File "/home/lcur1624/ae_flow/train.py", line 137, in <module>
    main(args)
  File "/home/lcur1624/ae_flow/train.py", line 102, in main
    eval_model(epoch, model, test_loader, _print=True)
  File "/home/lcur1624/ae_flow/train.py", line 66, in eval_model
    results['ACC'] = torchmetrics.Accuracy(task='binary', average='none')(pred, true)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/metric.py", line 236, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/metric.py", line 302, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/metric.py", line 390, in wrapped_func
    update(*args, **kwargs)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/classification/stat_scores.py", line 175, in update
    _binary_stat_scores_tensor_validation(preds, target, self.multidim_average, self.ignore_index)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/functional/classification/stat_scores.py", line 61, in _binary_stat_scores_tensor_validation
    _check_same_shape(preds, target)
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 40, in _check_same_shape
    if preds.shape != target.shape:
AttributeError: 'list' object has no attribute 'shape'
srun: error: r28n4: task 0: Exited with exit code 1
